---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: on-failure
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: ${app_domain}
    networks:
      - web
    volumes:
      - config_data:/app/config
      - icons_data:/app/public/icons
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`${app_domain}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - traefik.docker.network=web

networks:
  web:
    external: true

volumes:
  config_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${app_data_path}/config
  icons_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${app_data_path}/icons
